# Generated by Django 3.0.7 on 2020-06-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200611_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
